name: Update eprint list

on:
  push:
  schedule:
    - cron: "5 8 * * 0" # once per week

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, php-curl-class
    - name: run php
      env:
        osf_token: ${{ secrets.OSF_TOKEN }}
      run: |
        php engrxiv_prints.php -p$osf_token
    - name: upload csv to OSF
      env:
        osf_token: ${{ secrets.OSF_TOKEN }}
      run: |
        curl https://files.osf.io/v1/resources/j49t2/providers/osfstorage/5c2a32270e8efd0018cc8d79?kind=file -H "Authorization: Bearer $osf_token" --upload-file engrxiv-papers.csv
